// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBISHjRMUiDtBFrDD6mNJ42s6qvYck5jw',
    appId: '1:980180507972:web:6c556f1e4b25bc1b104b11',
    messagingSenderId: '980180507972',
    projectId: 'words-9d7cc',
    authDomain: 'words-9d7cc.firebaseapp.com',
    storageBucket: 'words-9d7cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdFwRbDTzKqXL4-tY9bs6ZNSGGSbGZH-0',
    appId: '1:980180507972:android:890e640c037bde6d104b11',
    messagingSenderId: '980180507972',
    projectId: 'words-9d7cc',
    storageBucket: 'words-9d7cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr_Tf6PQVIt4lYn4-7bivf1oiKZ5K30sE',
    appId: '1:980180507972:ios:57170ecff1f51740104b11',
    messagingSenderId: '980180507972',
    projectId: 'words-9d7cc',
    storageBucket: 'words-9d7cc.appspot.com',
    iosClientId:
        '980180507972-aqm39i7cbf7utg3glrek5fl83ibegrki.apps.googleusercontent.com',
    iosBundleId: 'com.nebulalabs.words',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr_Tf6PQVIt4lYn4-7bivf1oiKZ5K30sE',
    appId: '1:980180507972:ios:57170ecff1f51740104b11',
    messagingSenderId: '980180507972',
    projectId: 'words-9d7cc',
    storageBucket: 'words-9d7cc.appspot.com',
    iosClientId:
        '980180507972-aqm39i7cbf7utg3glrek5fl83ibegrki.apps.googleusercontent.com',
    iosBundleId: 'com.nebulalabs.words',
  );
}
